### ISSUE TITLE
Can you add support for ModBus RTU (serial)?

### ISSUE THREAD

**Issue by guywithcrookedface** [StevePo/jsModbus#10]
I really like the minimal bloat and dependencies this library has, but in my case I'm in need of a library that provides a means of connecting via a serial port.

**Comment by DRJ113** [comment]
I like it too.  Have you found a way to use it via a serial port?

**Comment by StevePo** [comment]
Have a look at https://github.com/Cloud-Automation/modbus. This project is deprecated. Since I separate the tcp and modbus part you could build it for serial communication very easily. Have a look at the code.
